# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-23 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
