# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200623_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
