# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0004_auto_20200623_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
            preserve_default=False,
        ),
    ]
