# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-30 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodsinfo_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='userId',
            new_name='user',
        ),
    ]
